const cities = [
  "Port Blair,Andaman and Nicobar Islands",
  "Faridabad,Haryana", "Gurgaon,Haryana", "Hisar,Haryana", "Rohtak,Haryana", "Panipat,Haryana",
  "Karnal,Haryana", "Sonipat,Haryana", "Yamunanagar,Haryana", "Panchkula,Haryana", "Bhiwani,Haryana",
  "Bahadurgarh,Haryana", "Jind,Haryana", "Sirsa,Haryana", "Thanesar,Haryana", "Kaithal,Haryana",
  "Palwal,Haryana", "Rewari,Haryana", "Hansi,Haryana", "Narnaul,Haryana", "Fatehabad,Haryana",
  "Gohana,Haryana", "Tohana,Haryana", "Narwana,Haryana", "Mandi Dabwali,Haryana", "Charkhi Dadri,Haryana",
  "Shahbad,Haryana", "Pehowa,Haryana", "Samalkha,Haryana", "Pinjore,Haryana", "Ladwa,Haryana",
  "Sohna,Haryana", "Safidon,Haryana", "Taraori,Haryana", "Mahendragarh,Haryana", "Ratia,Haryana",
  "Rania,Haryana", "Sarsod,Haryana",
  "Chennai,Tamil Nadu", "Coimbatore,Tamil Nadu", "Madurai,Tamil Nadu", "Tiruchirappalli,Tamil Nadu",
  "Salem,Tamil Nadu", "Tirunelveli,Tamil Nadu", "Tiruppur,Tamil Nadu", "Ranipet,Tamil Nadu",
  "Nagercoil,Tamil Nadu", "Thanjavur,Tamil Nadu", "Vellore,Tamil Nadu", "Kancheepuram,Tamil Nadu",
  "Erode,Tamil Nadu", "Tiruvannamalai,Tamil Nadu", "Pollachi,Tamil Nadu", "Rajapalayam,Tamil Nadu",
  "Sivakasi,Tamil Nadu", "Pudukkottai,Tamil Nadu", "Neyveli (TS),Tamil Nadu", "Nagapattinam,Tamil Nadu",
  "Viluppuram,Tamil Nadu", "Tiruchengode,Tamil Nadu", "Vaniyambadi,Tamil Nadu", "Theni Allinagaram,Tamil Nadu",
  "Udhagamandalam,Tamil Nadu", "Aruppukkottai,Tamil Nadu", "Paramakudi,Tamil Nadu", "Arakkonam,Tamil Nadu",
  "Virudhachalam,Tamil Nadu", "Srivilliputhur,Tamil Nadu", "Tindivanam,Tamil Nadu", "Virudhunagar,Tamil Nadu",
  "Karur,Tamil Nadu", "Valparai,Tamil Nadu", "Sankarankovil,Tamil Nadu", "Tenkasi,Tamil Nadu",
  "Palani,Tamil Nadu", "Pattukkottai,Tamil Nadu", "Tirupathur,Tamil Nadu", "Ramanathapuram,Tamil Nadu",
  "Udumalaipettai,Tamil Nadu", "Gobichettipalayam,Tamil Nadu", "Thiruvarur,Tamil Nadu", "Thiruvallur,Tamil Nadu",
  "Panruti,Tamil Nadu", "Namakkal,Tamil Nadu", "Thirumangalam,Tamil Nadu", "Vikramasingapuram,Tamil Nadu",
  "Nellikuppam,Tamil Nadu", "Rasipuram,Tamil Nadu", "Tiruttani,Tamil Nadu", "Nandivaram-Guduvancheri,Tamil Nadu",
  "Periyakulam,Tamil Nadu", "Pernampattu,Tamil Nadu", "Vellakoil,Tamil Nadu", "Sivaganga,Tamil Nadu",
  "Vadalur,Tamil Nadu", "Rameshwaram,Tamil Nadu", "Tiruvethipuram,Tamil Nadu", "Perambalur,Tamil Nadu",
  "Usilampatti,Tamil Nadu", "Vedaranyam,Tamil Nadu", "Sathyamangalam,Tamil Nadu", "Puliyankudi,Tamil Nadu",
  "Nanjikottai,Tamil Nadu", "Thuraiyur,Tamil Nadu", "Sirkali,Tamil Nadu", "Tiruchendur,Tamil Nadu",
  "Periyasemur,Tamil Nadu", "Sattur,Tamil Nadu", "Vandavasi,Tamil Nadu", "Tharamangalam,Tamil Nadu",
  "Tirukkoyilur,Tamil Nadu", "Oddanchatram,Tamil Nadu", "Palladam,Tamil Nadu", "Vadakkuvalliyur,Tamil Nadu",
  "Tirukalukundram,Tamil Nadu", "Uthamapalayam,Tamil Nadu", "Surandai,Tamil Nadu", "Sankari,Tamil Nadu",
  "Shenkottai,Tamil Nadu", "Vadipatti,Tamil Nadu", "Sholingur,Tamil Nadu", "Tirupathur,Tamil Nadu",
  "Manachanallur,Tamil Nadu", "Viswanatham,Tamil Nadu", "Polur,Tamil Nadu", "Panagudi,Tamil Nadu",
  "Uthiramerur,Tamil Nadu", "Thiruthuraipoondi,Tamil Nadu", "Pallapatti,Tamil Nadu", "Ponneri,Tamil Nadu",
  "Lalgudi,Tamil Nadu", "Natham,Tamil Nadu", "Unnamalaikadai,Tamil Nadu", "P.N.Patti,Tamil Nadu",
  "Tharangambadi,Tamil Nadu", "Tittakudi,Tamil Nadu", "Pacode,Tamil Nadu", "O' Valley,Tamil Nadu",
  "Suriyampalayam,Tamil Nadu", "Sholavandan,Tamil Nadu", "Thammampatti,Tamil Nadu", "Namagiripettai,Tamil Nadu",
  "Peravurani,Tamil Nadu", "Parangipettai,Tamil Nadu", "Pudupattinam,Tamil Nadu", "Pallikonda,Tamil Nadu",
  "Sivagiri,Tamil Nadu", "Punjaipugalur,Tamil Nadu", "Padmanabhapuram,Tamil Nadu", "Thirupuvanam,Tamil Nadu",
  "Indore,Madhya Pradesh", "Bhopal,Madhya Pradesh", "Jabalpur,Madhya Pradesh", "Gwalior,Madhya Pradesh",
  "Ujjain,Madhya Pradesh", "Sagar,Madhya Pradesh", "Ratlam,Madhya Pradesh", "Satna,Madhya Pradesh",
  "Murwara (Katni),Madhya Pradesh", "Morena,Madhya Pradesh", "Singrauli,Madhya Pradesh", "Rewa,Madhya Pradesh",
  "Vidisha,Madhya Pradesh", "Ganjbasoda,Madhya Pradesh", "Shivpuri,Madhya Pradesh", "Mandsaur,Madhya Pradesh",
  "Neemuch,Madhya Pradesh", "Nagda,Madhya Pradesh", "Itarsi,Madhya Pradesh", "Sarni,Madhya Pradesh",
  "Sehore,Madhya Pradesh", "Mhow Cantonment,Madhya Pradesh", "Seoni,Madhya Pradesh", "Balaghat,Madhya Pradesh",
  "Ashok Nagar,Madhya Pradesh", "Tikamgarh,Madhya Pradesh", "Shahdol,Madhya Pradesh", "Pithampur,Madhya Pradesh",
  "Alirajpur,Madhya Pradesh", "Mandla,Madhya Pradesh", "Sheopur,Madhya Pradesh", "Shajapur,Madhya Pradesh",
  "Panna,Madhya Pradesh", "Raghogarh-Vijaypur,Madhya Pradesh", "Sendhwa,Madhya Pradesh", "Sidhi,Madhya Pradesh",
  "Pipariya,Madhya Pradesh", "Shujalpur,Madhya Pradesh", "Sironj,Madhya Pradesh", "Pandhurna,Madhya Pradesh",
  "Nowgong,Madhya Pradesh", "Mandideep,Madhya Pradesh", "Sihora,Madhya Pradesh", "Raisen,Madhya Pradesh",
  "Lahar,Madhya Pradesh", "Maihar,Madhya Pradesh", "Sanawad,Madhya Pradesh", "Sabalgarh,Madhya Pradesh",
  "Umaria,Madhya Pradesh", "Porsa,Madhya Pradesh", "Narsinghgarh,Madhya Pradesh", "Malaj Khand,Madhya Pradesh",
  "Sarangpur,Madhya Pradesh", "Mundi,Madhya Pradesh", "Nepanagar,Madhya Pradesh", "Pasan,Madhya Pradesh",
  "Mahidpur,Madhya Pradesh", "Seoni-Malwa,Madhya Pradesh", "Rehli,Madhya Pradesh", "Manawar,Madhya Pradesh",
  "Rahatgarh,Madhya Pradesh", "Panagar,Madhya Pradesh", "Wara Seoni,Madhya Pradesh", "Tarana,Madhya Pradesh",
  "Sausar,Madhya Pradesh", "Rajgarh,Madhya Pradesh", "Niwari,Madhya Pradesh", "Mauganj,Madhya Pradesh",
  "Manasa,Madhya Pradesh", "Nainpur,Madhya Pradesh", "Prithvipur,Madhya Pradesh", "Sohagpur,Madhya Pradesh",
  "Nowrozabad (Khodargama),Madhya Pradesh", "Shamgarh,Madhya Pradesh", "Maharajpur,Madhya Pradesh",
  "Multai,Madhya Pradesh", "Pali,Madhya Pradesh", "Pachore,Madhya Pradesh", "Rau,Madhya Pradesh",
  "Mhowgaon,Madhya Pradesh", "Vijaypur,Madhya Pradesh", "Narsinghgarh,Madhya Pradesh",
  "Dhanbad,Jharkhand", "Ranchi,Jharkhand", "Jamshedpur,Jharkhand", "Bokaro Steel City,Jharkhand",
  "Deoghar,Jharkhand", "Phusro,Jharkhand", "Adityapur,Jharkhand", "Hazaribag,Jharkhand",
  "Giridih,Jharkhand", "Ramgarh,Jharkhand", "Jhumri Tilaiya,Jharkhand", "Saunda,Jharkhand",
  "Sahibganj,Jharkhand", "Medininagar (Daltonganj),Jharkhand", "Chaibasa,Jharkhand", "Chatra,Jharkhand",
  "Gumia,Jharkhand", "Dumka,Jharkhand", "Madhupur,Jharkhand", "Chirkunda,Jharkhand", "Pakaur,Jharkhand",
  "Simdega,Jharkhand", "Musabani,Jharkhand", "Mihijam,Jharkhand", "Patratu,Jharkhand", "Lohardaga,Jharkhand",
  "Tenu dam-cum-Kathhara,Jharkhand",
  "Aizawl,Mizoram", "Lunglei,Mizoram", "Saiha,Mizoram",
  "Dimapur,Nagaland", "Kohima,Nagaland", "Zunheboto,Nagaland", "Tuensang,Nagaland", "Wokha,Nagaland",
  "Mokokchung,Nagaland",
  "Shimla,Himachal Pradesh", "Mandi,Himachal Pradesh", "Solan,Himachal Pradesh", "Nahan,Himachal Pradesh",
  "Sundarnagar,Himachal Pradesh", "Palampur,Himachal Pradesh", "Kullu,Himachal Pradesh",
  "Agartala,Tripura", "Udaipur,Tripura", "Dharmanagar,Tripura", "Pratapgarh,Tripura", "Kailasahar,Tripura",
  "Belonia,Tripura", "Khowai,Tripura",
  "Visakhapatnam,Andhra Pradesh", "Vijayawada,Andhra Pradesh", "Guntur,Andhra Pradesh", "Nellore,Andhra Pradesh",
  "Kurnool,Andhra Pradesh", "Rajahmundry,Andhra Pradesh", "Kakinada,Andhra Pradesh", "Tirupati,Andhra Pradesh",
  "Anantapur,Andhra Pradesh", "Kadapa,Andhra Pradesh", "Vizianagaram,Andhra Pradesh", "Eluru,Andhra Pradesh",
  "Ongole,Andhra Pradesh", "Nandyal,Andhra Pradesh", "Machilipatnam,Andhra Pradesh", "Adoni,Andhra Pradesh",
  "Tenali,Andhra Pradesh", "Chittoor,Andhra Pradesh", "Hindupur,Andhra Pradesh", "Proddatur,Andhra Pradesh",
  "Bhimavaram,Andhra Pradesh", "Madanapalle,Andhra Pradesh", "Guntakal,Andhra Pradesh", "Dharmavaram,Andhra Pradesh",
  "Gudivada,Andhra Pradesh", "Srikakulam,Andhra Pradesh", "Narasaraopet,Andhra Pradesh", "Rajampet,Andhra Pradesh",
  "Tadpatri,Andhra Pradesh", "Tadepalligudem,Andhra Pradesh", "Chilakaluripet,Andhra Pradesh", "Yemmiganur,Andhra Pradesh",
  "Kadiri,Andhra Pradesh", "Chirala,Andhra Pradesh", "Anakapalle,Andhra Pradesh", "Kavali,Andhra Pradesh",
  "Palacole,Andhra Pradesh", "Sullurpeta,Andhra Pradesh", "Tanuku,Andhra Pradesh", "Rayachoti,Andhra Pradesh",
  "Srikalahasti,Andhra Pradesh", "Bapatla,Andhra Pradesh", "Naidupet,Andhra Pradesh", "Nagari,Andhra Pradesh",
  "Gudur,Andhra Pradesh", "Vinukonda,Andhra Pradesh", "Narasapuram,Andhra Pradesh", "Nuzvid,Andhra Pradesh",
  "Markapur,Andhra Pradesh", "Ponnur,Andhra Pradesh", "Kandukur,Andhra Pradesh", "Bobbili,Andhra Pradesh",
  "Rayadurg,Andhra Pradesh", "Samalkot,Andhra Pradesh", "Jaggaiahpet,Andhra Pradesh", "Tuni,Andhra Pradesh",
  "Amalapuram,An dhra Pradesh", "Bheemunipatnam,Andhra Pradesh", "Venkatagiri,Andhra Pradesh", "Sattenapalle,Andhra Pradesh",
  "Pithapuram,Andhra Pradesh", "Palasa Kasibugga,Andhra Pradesh", "Parvathipuram,Andhra Pradesh", "Macherla,Andhra Pradesh",
  "Gooty,Andhra Pradesh", "Salur,Andhra Pradesh", "Mandapeta,Andhra Pradesh", "Jammalamadugu,Andhra Pradesh",
  "Peddapuram,Andhra Pradesh", "Punganur,Andhra Pradesh", "Nidadavole,Andhra Pradesh", "Repalle,Andhra Pradesh",
  "Ramachandrapuram,Andhra Pradesh", "Kovvur,Andhra Pradesh", "Tiruvuru,Andhra Pradesh", "Uravakonda,Andhra Pradesh",
  "Narsipatnam,Andhra Pradesh", "Yerraguntla,Andhra Pradesh", "Pedana,Andhra Pradesh", "Puttur,Andhra Pradesh",
  "Renigunta,Andhra Pradesh", "Rajam,Andhra Pradesh", "Srisailam Project (Right Flank Colony) Township,Andhra Pradesh",
  "Ludhiana,Punjab", "Patiala,Punjab", "Amritsar,Punjab", "Jalandhar,Punjab", "Bathinda,Punjab",
  "Pathankot,Punjab", "Hoshiarpur,Punjab", "Batala,Punjab", "Moga,Punjab", "Malerkotla,Punjab",
  "Khanna,Punjab", "Mohali,Punjab", "Barnala,Punjab", "Firozpur,Punjab", "Phagwara,Punjab",
  "Kapurthala,Punjab", "Zirakpur,Punjab", "Kot Kapura,Punjab", "Faridkot,Punjab", "Muktsar,Punjab",
  "Rajpura,Punjab", "Sangrur,Punjab", "Fazilka,Punjab", "Gurdaspur,Punjab", "Kharar,Punjab",
  "Gobindgarh,Punjab", "Mansa,Punjab", "Malout,Punjab", "Nabha,Punjab", "Tarn Taran,Punjab",
  "Jagraon,Punjab", "Sunam,Punjab", "Dhuri,Punjab", "Firozpur Cantt.,Punjab", "Sirhind Fatehgarh Sahib,Punjab",
  "Rupnagar,Punjab", "Jalandhar Cantt.,Punjab", "Samana,Punjab", "Nawanshahr,Punjab", "Rampura Phul,Punjab",
  "Nangal,Punjab", "Nakodar,Punjab", "Zira,Punjab", "Patti,Punjab", "Raikot,Punjab",
  "Longowal,Punjab", "Urmar Tanda,Punjab", "Morinda, India,Punjab", "Phillaur,Punjab", "Pattran,Punjab",
  "Qadian,Punjab", "Sujanpur,Punjab", "Mukerian,Punjab", "Talwara,Punjab",
  "Chandigarh,Chandigarh",
  "Jaipur,Rajasthan", "Jodhpur,Rajasthan", "Bikaner,Rajasthan", "Udaipur,Rajasthan", "Ajmer,Rajasthan",
  "Bhilwara,Rajasthan", "Alwar,Rajasthan", "Bharatpur,Rajasthan", "Pali,Rajasthan", "Barmer,Rajasthan",
  "Sikar,Rajasthan", "Tonk,Rajasthan", "Sadulpur,Rajasthan", "Sawai Madhopur,Rajasthan", "Nagaur,Rajasthan",
  "Makrana,Rajasthan", "Sujangarh,Rajasthan", "Sardarshahar,Rajasthan", "Ladnu,Rajasthan", "Ratangarh,Rajasthan",
  "Nokha,Rajasthan", "Nimbahera,Rajasthan", "Suratgarh,Rajasthan", "Rajsamand,Rajasthan", "Lachhmangarh,Rajasthan",
  "Rajgarh (Churu),Rajasthan", "Nasirabad,Rajasthan", "Nohar,Rajasthan", "Phalodi,Rajasthan", "Nathdwara,Rajasthan",
  "Pilani,Rajasthan", "Merta City,Rajasthan", "Sojat,Rajasthan", "Neem-Ka-Thana,Rajasthan", "Sirohi,Rajasthan",
  "Pratapgarh,Rajasthan", "Rawatbhata,Rajasthan", "Sangaria,Rajasthan", "Lalsot,Rajasthan", "Pilibanga,Rajasthan",
  "Pipar City,Rajasthan", "Taranagar,Rajasthan", "Vijainagar, Ajmer,Rajasthan", "Sumerpur,Rajasthan", "Sagwara,Rajasthan",
  "Ramganj Mandi,Rajasthan", "Lakheri,Rajasthan", "Udaipurwati,Rajasthan", "Losal,Rajasthan", "Sri Madhopur,Rajasthan",
  "Ramngarh,Rajasthan", "Rawatsar,Rajasthan", "Rajakhera,Rajasthan", "Shahpura,Rajasthan", "Shahpura,Rajasthan",
  "Raisinghnagar,Rajasthan", "Malpura,Rajasthan", "Nadbai,Rajasthan", "Sanchore,Rajasthan", "Nagar,Rajasthan",
  "Rajgarh (Alwar),Rajasthan", "Sheoganj,Rajasthan", "Sadri,Rajasthan", "Todaraisingh,Rajasthan", "Todabhim,Rajasthan",
  "Reengus,Rajasthan", "Rajaldesar,Rajasthan", "Sadulshahar,Rajasthan", "Sambhar,Rajasthan", "Prantij,Rajasthan",
  "Mount Abu,Rajasthan", "Mangrol,Rajasthan", "Phulera,Rajasthan", "Mandawa,Rajasthan", "Pindwara,Rajasthan",
  "Mandalgarh,Rajasthan", "Takhatgarh,Rajasthan",
  "Guwahati,Assam", "Silchar,Assam", "Dibrugarh,Assam", "Nagaon,Assam", "Tinsukia,Assam",
  "Jorhat,Assam", "Bongaigaon City,Assam", "Dhubri,Assam", "Diphu,Assam", "North Lakhimpur,Assam",
  "Tezpur,Assam", "Karimganj,Assam", "Sibsagar,Assam", "Goalpara,Assam", "Barpeta,Assam",
  "Lanka,Assam", "Lumding,Assam", "Mankachar,Assam", "Nalbari,Assam", "Rangia,Assam",
  "Margherita,Assam", "Mangaldoi,Assam", "Silapathar,Assam", "Mariani,Assam", "Marigaon,Assam",
  "Bhubaneswar,Odisha", "Cuttack,Odisha", "Raurkela,Odisha", "Brahmapur,Odisha", "Sambalpur,Odisha",
  "Puri,Odisha", "Baleshwar Town,Odisha", "Baripada Town,Odisha", "Bhadrak,Odisha", "Balangir,Odisha",
  "Jharsuguda,Odisha", "Bargarh,Odisha", "Paradip,Odisha", "Bhawanipatna,Odisha", "Dhenkanal,Odisha",
  "Barbil,Odisha", "Kendujhar,Odisha", "Sunabeda,Odisha", "Rayagada,Odisha", "Jatani,Odisha",
  "Byasanagar,Odisha", "Kendrapara,Odisha", "Rajagangapur,Odisha", "Parlakhemundi,Odisha", "Talcher,Odisha",
  "Sundargarh,Odisha", "Phulabani,Odisha", "Pattamundai,Odisha", "Titlagarh,Odisha", "Nabarangapur,Odisha",
  "Soro,Odisha", "Malkangiri,Odisha", "Rairangpur,Odisha", "Tarbha,Odisha",
  "Raipur,Chhattisgarh", "Bhilai Nagar,Chhattisgarh", "Korba,Chhattisgarh", "Bilaspur,Chhattisgarh", "Durg,Chhattisgarh",
  "Rajnandgaon,Chhattisgarh", "Jagdalpur,Chhattisgarh", "Raigarh,Chhattisgarh", "Ambikapur,Chhattisgarh",
  "Mahasamund,Chhattisgarh", "Dhamtari,Chhattisgarh", "Chirmiri,Chhattisgarh", "Bhatapara,Chhattisgarh",
  "Dalli-Rajhara,Chhattisgarh", "Naila Janjgir,Chhattisgarh", "Tilda Newra,Chhattisgarh", "Mungeli,Chhattisgarh",
  "Manendragarh,Chhattisgarh", "Sakti,Chhattisgarh",
  "Srinagar,Jammu and Kashmir", "Jammu,Jammu and Kashmir", "Baramula,Jammu and Kashmir", "Anantnag,Jammu and Kashmir",
  "Sopore,Jammu and Kashmir", "KathUrban Agglomeration,Jammu and Kashmir", "Rajauri,Jammu and Kashmir",
  "Punch,Jammu and Kashmir", "Udhampur,Jammu and Kashmir",
  "Bengaluru,Karnataka", "Hubli-Dharwad,Karnataka", "Belagavi,Karnataka", "Mangaluru,Karnataka", "Davanagere,Karnataka",
  "Ballari,Karnataka", "Mysore,Karnataka", "Tumkur,Karnataka", "Shivamogga,Karnataka", "Raayachuru,Karnataka",
  "Robertson Pet,Karnataka", "Kolar,Karnataka", "Mandya,Karnataka", "Udupi,Karnataka", "Chikkamagaluru,Karnataka",
  "Karwar,Karnataka", "Ranebennuru,Karnataka", "Ranibennur,Karnataka", "Ramanagaram,Karnataka", "Gokak,Karnataka",
  "Yadgir,Karnataka", "Rabkavi Banhatti,Karnataka", "Shahabad,Karnataka", "Sirsi,Karnataka", "Sindhnur,Karnataka",
  "Tiptur,Karnataka", "Arsikere,Karnataka", "Nanjangud,Karnataka", "Sagara,Karnataka", "Sira,Karnataka",
  "Puttur,Karnataka", "Athni,Karnataka", "Mulbagal,Karnataka", "Surapura,Karnataka", "Siruguppa,Karnataka",
  "Mudhol,Karnataka", "Sidlaghatta,Karnataka", "Shahpur,Karnataka", "Saundatti-Yellamma,Karnataka", "Wadi,Karnataka",
  "Manvi,Karnataka", "Nelamangala,Karnataka", "Lakshmeshwar,Karnataka", "Ramdurg,Karnataka", "Nargund,Karnataka",
  "Tarikere,Karnataka", "Malavalli,Karnataka", "Savanur,Karnataka", "Lingsugur,Karnataka", "Vijayapura,Karnataka",
  "Sankeshwara,Karnataka", "Madikeri,Karnataka", "Talikota,Karnataka", "Sedam,Karnataka", "Shikaripur,Karnataka",
  "Mahalingapura,Karnataka", "Mudalagi,Karnataka", "Muddebihal,Karnataka", "Pavagada,Karnataka", "Malur,Karnataka",
  "Sindhagi,Karnataka", "Sanduru,Karnataka", "Afzalpur,Karnataka", "Maddur,Karnataka", "Madhugiri,Karnataka",
  "Tekkalakote,Karnataka", "Terdal,Karnataka", "Mudabidri,Karnataka", "Magadi,Karnataka", "Navalgund,Karnataka",
  "Shiggaon,Karnataka", "Shrirangapattana,Karnataka", "Sindagi,Karnataka", "Sakaleshapura,Karnataka",
  "Srinivaspur,Karnataka", "Ron,Karnataka", "Mundargi,Karnataka", "Sadalagi,Karnataka", "Piriyapatna,Karnataka",
  "Adyar,Karnataka",
  "Imphal,Manipur", "Thoubal,Manipur", "Lilong,Manipur", "Mayang Imphal,Manipur",
  "Thiruvananthapuram,Kerala", "Kochi,Kerala", "Kozhikode,Kerala", "Kollam,Kerala", "Thrissur,Kerala",
  "Palakkad,Kerala", "Alappuzha,Kerala", "Malappuram,Kerala", "Ponnani,Kerala", "Vatakara,Kerala",
  "Kanhangad,Kerala", "Taliparamba,Kerala", "Koyilandy,Kerala", "Neyyattinkara,Kerala", "Kayamkulam,Kerala",
  "Nedumangad,Kerala", "Kannur,Kerala", "Tirur,Kerala", "Kottayam,Kerala", "Kasaragod,Kerala",
  "Kunnamkulam,Kerala", "Ottappalam,Kerala", "Thiruvalla,Kerala", "Thodupuzha,Kerala", "Chalakudy,Kerala",
  "Changanassery,Kerala", "Punalur,Kerala", "Nilambur,Kerala", "Cherthala,Kerala", "Perinthalmanna,Kerala",
  "Mattannur,Kerala", "Shoranur,Kerala", "Varkala,Kerala", "Paravoor,Kerala", "Pathanamthi"
];


